alias sudo="sudo "
alias mkdir="mkdir -p"
alias rm="rm -v"
alias tarup="tar -cvzf"
alias untar="tar -zxvf"

alias cdcs="cd ~/Repositories/cs"
alias cdr="cd ~/Repositories/"
alias cdt="cd ~/Repositories/taghub"
alias cdb="cd ~/Repositories/bareapp"
alias cds="cd ~/Repositories/scripts"
alias cdp="cd ~/Repositories/projects"
alias cdg="cd ~/Repositories/pandagrader"
alias cdc="cd ~/Repositories/current"
alias cdcl="cd ~/Documents/Class"
alias cd194="cd ~/Documents/Class/CS194"
alias cd169="cd ~/Documents/Class/CS169"
alias cd122="cd ~/Documents/Class/EE122"
alias cdcc="cd ~/Repositories/cc/"
alias cdenv="cd ~/Repositories/env"
alias cdl="cd /palaran/code"
alias cdh="cd ~/.homework"
alias cdw="cd /palaran/current"
alias cdv="cd /palaran/code/ninja/vagrant"
alias cdlj="cd /palaran/code/jsm"
alias cdrs="cd /palaran/code/rockstar"
alias cdrs2="cd /palanran/code/rockstar2"
alias cdrs3="cd /palaran/code/rockstar3"
alias myenv="cd -P ~/.env"

alias ch="choose"

alias envup="(cdenv ; git pull ; git subup)"
alias envst="(cdenv ; git st)"

alias railss="RAILS_ENV=staging bundle exec rails s"

alias slem="emacs -q -l ~/.emacs.slim"
alias s="e -q -l ~/.emacs.slim"